os: linux
dist: trusty

language: php

if: tag IS blank

stages:
  - test
  - deploy

before_script:
  - nvm install 10
  - make install

script: make tests

jobs:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0
    - stage: deploy
      deploy:
        cleanup: false
        provider: script
        script: make
      if: branch = master AND type = push AND fork = false