version: '3'
services:
  app:
    build:
      context: ./.docker
    volumes:
      - ./:/code
    links:
      - "mysql"
    user: ${UID:-1000}:${GID:-1000}
    depends_on:
      - mysql
    entrypoint: make local_test
    env_file:
      - ./.env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - WP_VERSION=${WP_VERSION}
      - WC_VERSION=${WC_VERSION}
      - SKIP_DB_CREATE=true
  mysql:
    image: mysql:5.7
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
